# Generated by Django 4.2.7 on 2023-12-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeaward',
            name='GetDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
