# Generated by Django 4.2.7 on 2023-12-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_rename_duration_minutes_animelist_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='animationstudio',
            name='FoundedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toptierwaifu',
            name='resultDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
