# Generated by Django 4.2.7 on 2023-12-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_alter_bestanimeofalltime_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='toptierwaifu',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
